### ISSUE TITLE
Scan().File Access Violation Error

### ISSUE THREAD

**Issue by radiolondra** [MirekVales/MVsDotNetAMSIClient#1]
Windows 10 Enterprise 21H1
Visual Studio 2017
Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz   2.40 GHz
16GB RAM

I created a new WinForm project using .NET 4.7.1 framework version. 
I Installed via NuGet tool MVsDotNetAMSIClient.
I created a Button with the following OnClick event:

```
var filename = @"C:\temp\TestCopia.exe";
if (File.Exists(filename)) {
    var result = new Scan().File(filename);
}
```
The call to `new Scan().File` generates an `Access Violation Error`.

Am I doing something wrong or missed something?
Any idea?
Thanks

**Comment by radiolondra** [comment]
Ok,my fault
MVsDotNetAMSIClient is a netstandard dll, I cannot use WinForm as base project.
Not mind
Thanks anyway

**Comment by klimkam** [comment]
> Ok,my fault MVsDotNetAMSIClient is a netstandard dll, I cannot use WinForm as base project. Not mind Thanks anyway

I have met a similar issue, but with Scan.Buffer. Can you please explain, how did you solve it?
